name: Main testing workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.9"
            toxfactor: py39
            ignore-typecheck-outcome: false
            ignore-test-outcome: false
          - python-version: "pypy3.9"
            toxfactor: py39
            ignore-typecheck-outcome: false
            ignore-test-outcome: true
          - python-version: "3.10"
            toxfactor: py310
            ignore-typecheck-outcome: false
            ignore-test-outcome: false
          - python-version: "pypy3.10"
            toxfactor: pypy310
            ignore-typecheck-outcome: false
            ignore-test-outcome: false
          - python-version: "3.11"
            toxfactor: py311
            ignore-typecheck-outcome: false
            ignore-test-outcome: false
          - python-version: "pypy3.11"
            toxfactor: pypy311
            ignore-typecheck-outcome: false
            ignore-test-outcome: false
          - python-version: "3.12"
            toxfactor: py312
            ignore-typecheck-outcome: false
            ignore-test-outcome: false
          - python-version: "3.13"
            toxfactor: py313
            ignore-typecheck-outcome: false
            ignore-test-outcome: false

    steps:
    - uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        # Install a specific version of uv.
        version: "0.6.2"
        enable-cache: 'true'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dev dependencies
      run: |
        uv sync --group dev

    - name: Type checking
      # Ignore errors for older pythons
      continue-on-error: ${{ matrix.ignore-typecheck-outcome }}
      run: |
        source .venv/bin/activate
        tox -e mypy

    - name: Test with tox
      continue-on-error: ${{ matrix.ignore-test-outcome }}
      run: |
        source .venv/bin/activate
        coverage erase
        tox run -f ${{ matrix.toxfactor }}
        coverage combine
        coverage xml

    - uses: codecov/codecov-action@v3
      with:
        # Explicitly using the token in order to avoid Codecov rate limit errors
        # See https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        verbose: true # optional (default = false)
